Update old dependencies for lts-13.x
Since I want to use Hakyll with lts-13.x, I updated the old
dependencies.

Note: I used Travis CI for testing. Compared with CircleCI, I did not
have to make comlicated settings. I may possibly send a pull request to
update CI relationship. It was hard to use TravisCI in the past, but as
GHC's perfomance got higher, it's okay now!

Squashed: https://github.com/Hexirp/hakyll/tree/lts-13.0

----

Squashed commit of the following:

commit 65e7ac9e1a92c9e039fba7e31687f1ba0f8fd033
Author: Hexirp <Hexirp@users.noreply.github.com>
Date:   Sat Jan 12 10:01:23 2019 +0900

    Revert the changes for testing

    If I could figure out what kind of obstacles it is when building
    Hakyll, this changes is no longer necessary.

commit fe6238faa56ebe67815ef7e1c25c53c80b7906cb
Author: Hexirp <Hexirp@users.noreply.github.com>
Date:   Mon Jan 7 20:15:14 2019 +0900

    Bump stack resolver version to nightly-2019-01-07

    I am going to see if it can be added to Stackage. lrucache was
    re-enabled.

    See: https://github.com/commercialhaskell/stackage/pull/4277

commit 7e7f3f7bd775a1731ef94f61286e165cb7497a86
Author: Hexirp <Hexirp@users.noreply.github.com>
Date:   Sat Jan 5 22:43:37 2019 +0900

    Update cabal to relax upper bounds for containers and tasty

    I committed this commit to fix this error.

    Error: While constructing the build plan, the following exceptions were
    encountered:
    In the dependencies for hakyll-4.12.4.0(+buildWebsite
    +checkExternal
    +previewServer
    +usePandoc
    +watchServer):
        containers-0.6.0.1 from stack configuration does not match >=0.3 && <0.6
                           (latest matching version is 0.5.11.0)
        tasty-1.2 from stack configuration does not match >=0.11 && <1.2  (latest
                  matching version is 1.1.0.4)
    needed since hakyll is a build target.
    Some different approaches to resolving this:
      * Set 'allow-newer: true'
        in /home/travis/.stack/config.yaml to ignore all version constraints and build anyway.
      * Consider trying 'stack solver', which uses the cabal-install solver to
        attempt to find some working build configuration. This can be convenient
        when dealing with many complicated constraint errors, but results may be
        unpredictable.
      * Recommended action: try adding the following to your extra-deps
        in /home/travis/build/Hexirp/hakyll/stack.yaml:
    containers-0.5.11.0@sha256:28ad7337057442f75bc689315ab4ec7bdf5e6b2c39668f306672cecd82c02798
    tasty-1.1.0.4@sha256:1310ceed449b3227614b329a1672a2c5bb046cb49e281996523567b3b0ad9ecc

    https://travis-ci.org/Hexirp/hakyll/builds/475694909

commit 5390de6c3e2e2b55f74626da3954bf213a41aade
Author: Hexirp <Hexirp@users.noreply.github.com>
Date:   Sat Jan 5 22:36:08 2019 +0900

    Update stack.yaml to use updated lrucache

    I used it because I made lrucache correspond to lts-13.0.

commit 9772467c7103c0e48442e52680d7cc99b7dc9ae6
Author: Hexirp <Hexirp@users.noreply.github.com>
Date:   Sat Jan 5 21:57:34 2019 +0900

    Update .travis.yml to test this package

    I forgot to set it.

commit 23187c2062f7186c5e3967a4f34c50767670e4ec
Author: Hexirp <Hexirp@users.noreply.github.com>
Date:   Sat Jan 5 21:49:24 2019 +0900

    Update cabal to relax upper bounds for pandoc

    I committed this commit to fix this error. I missed another
    dependency on pandoc.

    Error: While constructing the build plan, the following exceptions were
    encountered:
    In the dependencies for hakyll-4.12.4.0(+buildWebsite
    +checkExternal
    +previewServer
    +usePandoc
    +watchServer):
        lrucache must match >=1.1.1 && <1.3, but the stack configuration has no
                 specified version  (latest matching version is 1.2.0.1)
        pandoc-2.5 from stack configuration does not match >=2.0.5 && <2.5  (latest
                   matching version is 2.4)
    needed since hakyll is a build target.
    Some different approaches to resolving this:
      * Consider trying 'stack solver', which uses the cabal-install solver to
        attempt to find some working build configuration. This can be convenient
        when dealing with many complicated constraint errors, but results may be
        unpredictable.
      * Recommended action: try adding the following to your extra-deps
        in /home/travis/build/Hexirp/hakyll/stack.yaml:
    lrucache-1.2.0.1@sha256:18fc3d7052012c7ab3cd395160f34b53c5e1ec5379cc45185baf35b90ffadc2e
    pandoc-2.4@sha256:f7ff25413b211d9744f6492ba0407b7768ed0a52d1b902e491074c902653744f

    https://travis-ci.org/Hexirp/hakyll/builds/475671737

commit 09164cca44607b8c98c6e0dfa5384b665dec6597
Author: Hexirp <Hexirp@users.noreply.github.com>
Date:   Sat Jan 5 20:38:00 2019 +0900

    Update cabal to relax upper bounds for containers and pandoc

    I committed this commit to fix this error. Since lrucache does not
    exist in lts-13.x, I need to put lrucache in lts-13.x.

    Error: While constructing the build plan, the following exceptions were
    encountered:
    In the dependencies for hakyll-4.12.4.0(+buildWebsite
    +checkExternal
    +previewServer
    +usePandoc
    +watchServer):
        containers-0.6.0.1 from stack configuration does not match >=0.3 && <0.6
                           (latest matching version is 0.5.11.0)
        lrucache must match >=1.1.1 && <1.3, but the stack configuration has no
                 specified version  (latest matching version is 1.2.0.1)
        pandoc-2.5 from stack configuration does not match >=2.0.5 && <2.5  (latest
                   matching version is 2.4)
    needed since hakyll is a build target.
    Some different approaches to resolving this:
      * Consider trying 'stack solver', which uses the cabal-install solver to
        attempt to find some working build configuration. This can be convenient
        when dealing with many complicated constraint errors, but results may be
        unpredictable.
      * Recommended action: try adding the following to your extra-deps
        in /home/travis/build/Hexirp/hakyll/stack.yaml:
    containers-0.5.11.0@sha256:28ad7337057442f75bc689315ab4ec7bdf5e6b2c39668f306672cecd82c02798
    lrucache-1.2.0.1@sha256:18fc3d7052012c7ab3cd395160f34b53c5e1ec5379cc45185baf35b90ffadc2e
    pandoc-2.4@sha256:f7ff25413b211d9744f6492ba0407b7768ed0a52d1b902e491074c902653744f

    https://travis-ci.org/Hexirp/hakyll/builds/475668223

commit 3d0b598871732f4aea6035946ffc9a22d6b62b59
Author: Hexirp <Hexirp@users.noreply.github.com>
Date:   Sat Jan 5 20:18:08 2019 +0900

    Update stack.yaml to use ghc-8.6.3

    I was watching the build by TravisCI and I noticed that stack was
    trying to download ghc-8.4.2. It was obvious that the build would
    fail, so I canceled it. I used ghc-8.6.3 for lts-13.0, so I commented
    out that setting in stack.yaml.

    https://travis-ci.org/Hexirp/hakyll/builds/475665636

commit 5b16608bc3f412bf64a1ecfbbdc21bf7c46f8f9d
Author: Hexirp <Hexirp@users.noreply.github.com>
Date:   Sat Jan 5 20:08:27 2019 +0900

    Fix '.travis.yaml' to '.travis.yml'

    This is a stupid mistake! However, I think TravisCI is tolerant.

commit 2c4d5af67b0e0563b579418603f06ce51d8b4b3d
Author: Hexirp <Hexirp@users.noreply.github.com>
Date:   Sat Jan 5 20:03:30 2019 +0900

    Add .travis.yaml

    Because my PC is low performance, I use TravisCI to build this.
    In addition, I would like to keep an error message when building.
    I think that it will expire if I do not take a special way when
    building this, but I think I'll start with the simplest setting.

commit 3994cec66d9c94cd337f38b4748bce063cb43ea0
Author: Hexirp <Hexirp@users.noreply.github.com>
Date:   Sat Jan 5 19:56:31 2019 +0900

    Bump stack resolver version to lts-13.0

    I am trying to be able to build Hakyll with lts-13.0. Since lots of
    packages have been updated in lts-13.0, I will disable extra-deps.
    I think I'll start with the simplest setting.