CI: do not cache Cabal artifacts
Apparently this caching is broken, because I'm getting the following
errors:

    ##[group]Run cabal update
    ␛[36;1mcabal update␛[0m
    ␛[36;1mcabal freeze␛[0m
    shell: /usr/bin/bash -e {0}
    ##[endgroup]
    Downloading the latest package list from hackage.haskell.org
    Package list of hackage.haskell.org is up to date.
    The index-state is set to 2023-06-10T20:17:53Z.
    Resolving dependencies...
    Wrote freeze file: /home/runner/work/hakyll/hakyll/cabal.project.freeze
    ##[group]Run actions/cache@v1
    with:
      path: /home/runner/.cabal/store
      key: Linux-9.2.7-1600b5355edcff94a143de40f9fff1f59e7677868c383b91a09dac50a7f04497
    ##[endgroup]
    Cache Size: ~144 MB (151229565 B)
    [command]/usr/bin/tar -xz -f /home/runner/work/_temp/6367b65e-ea25-4839-ab38-b4d827d2b121/cache.tgz -C /home/runner/.cabal/store
    Cache restored from key: Linux-9.2.7-1600b5355edcff94a143de40f9fff1f59e7677868c383b91a09dac50a7f04497
    ##[group]Run cabal configure --enable-tests --enable-benchmarks --test-show-details=direct
    ␛[36;1mcabal configure --enable-tests --enable-benchmarks --test-show-details=direct␛[0m
    ␛[36;1mcabal build all␛[0m
    shell: /usr/bin/bash -e {0}
    ##[endgroup]
    Config file path source is default config file.
    Config file not found: /home/runner/.cabal/config
    Writing default configuration to /home/runner/.cabal/config
    Warning: The package list for 'hackage.haskell.org' does not exist. Run 'cabal
    update' to download it.
    Warning: Requested index-state 2023-06-10T20:17:53Z is newer than
    'hackage.haskell.org'! Falling back to older state ().
    Resolving dependencies...
    Error: cabal: Could not resolve dependencies:
    [__0] trying: hakyll-4.16.0.0 (user goal)
    [__1] trying: hakyll:+usepandoc
    [__2] unknown package: pandoc (dependency of hakyll +usepandoc)
    [__2] fail (backjumping, conflict set: hakyll, pandoc, hakyll:usepandoc)
    After searching the rest of the dependency tree exhaustively, these were the
    goals I've had most trouble fulfilling: hakyll, hakyll:usepandoc, pandoc

    ##[error]Process completed with exit code 1.