CI: drop GHC 8.6.5
warp fails to build:

    Failed to build warp-3.3.26.
    Build log (
    C:\cabal\logs\ghc-8.6.5\warp-3.3.26-6532597186375e75cba91c6534d27ffe8796a2d0.log
    ):
    Preprocessing library for warp-3.3.26..
    Building library for warp-3.3.26..
    [ 1 of 33] Compiling Network.Wai.Handler.Warp.Date ( Network\Wai\Handler\Warp\Date.hs, dist\build\Network\Wai\Handler\Warp\Date.o )
    Error: cabal-3.8.1.0.exe: Failed to build warp-3.3.26 (which is required by
    test:hakyll-tests from hakyll-4.16.0.0 and exe:hakyll-init from
    hakyll-4.16.0.0). See the build log above for details.
    [ 2 of 33] Compiling Network.Wai.Handler.Warp.FdCache ( Network\Wai\Handler\Warp\FdCache.hs, dist\build\Network\Wai\Handler\Warp\FdCache.o )

    [ 3 of 33] Compiling Network.Wai.Handler.Warp.HashMap ( Network\Wai\Handler\Warp\HashMap.hs, dist\build\Network\Wai\Handler\Warp\HashMap.o )
    [ 4 of 33] Compiling Network.Wai.Handler.Warp.Imports ( Network\Wai\Handler\Warp\Imports.hs, dist\build\Network\Wai\Handler\Warp\Imports.o )
    [ 5 of 33] Compiling Network.Wai.Handler.Warp.FileInfoCache ( Network\Wai\Handler\Warp\FileInfoCache.hs, dist\build\Network\Wai\Handler\Warp\FileInfoCache.o )
    [ 6 of 33] Compiling Network.Wai.Handler.Warp.Counter ( Network\Wai\Handler\Warp\Counter.hs, dist\build\Network\Wai\Handler\Warp\Counter.o )
    [ 7 of 33] Compiling Network.Wai.Handler.Warp.PackInt ( Network\Wai\Handler\Warp\PackInt.hs, dist\build\Network\Wai\Handler\Warp\PackInt.o )
    [ 8 of 33] Compiling Network.Wai.Handler.Warp.ReadInt ( Network\Wai\Handler\Warp\ReadInt.hs, dist\build\Network\Wai\Handler\Warp\ReadInt.o )
    [ 9 of 33] Compiling Network.Wai.Handler.Warp.ResponseHeader ( Network\Wai\Handler\Warp\ResponseHeader.hs, dist\build\Network\Wai\Handler\Warp\ResponseHeader.o )
    [10 of 33] Compiling Network.Wai.Handler.Warp.Types ( Network\Wai\Handler\Warp\Types.hs, dist\build\Network\Wai\Handler\Warp\Types.o )

    Network\Wai\Handler\Warp\Types.hs:10:1: error:
    Error:     Could not load module ‘Data.X509’
        It is a member of the hidden package ‘x509-1.7.7’.
        Perhaps you need to add ‘x509’ to the build-depends in your .cabal file.
        Use -v to see a list of the files searched for.
       |
    10 | import Data.X509
       | ^^^^^^^^^^^^^^^^
    Error: Process completed with exit code 1.

Apparently the support was dropped in some transitive dependency. Since
8.6 branch is quite old now, I'll just drop support too.